llm:
  platform: "deepseek"
  model: "deepseek-chat"
  api_key: "sk-27642e4744b1489b88adbc39f76f5636"
  temperature: 0.7
  max_tokens: 4096

redis:
  host: "localhost"
  port: 6379
  db: 3
  password: 209020357

mongodb:
  username: "root"
  password: 209020357
  host: "10.99.65.75"
  port: 27017
  db_name: "news"